name: CI/CD pipeline
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: This is Build Step 
        run: echo "Successfully Build"

  Test:
    runs-on: ubuntu-latest
    steps: 
    - name: This is Test Step 
      run: echo "tested successfully"

  Deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: This is Deploy Step 
      run: echo "deployed successfully"
